### ISSUE TITLE
兄弟 左右按钮点击的事件怎么处理

### ISSUE THREAD

**Issue by Dhy521** [JerryChan123/ReSwipeCard#6]
左右点击 左滑右滑  怎么处理阿  我用的也是内个大佬的demo   但是他那边没有写这个 你是怎么处理的？

**Comment by JerryChan123** [comment]
额，我不太明白你的意思，如果是用我写的，这里面写的应该很清楚的：
[https://github.com/JerryChan123/ReSwipeCard/blob/master/app/src/main/java/com/lin/reswipecard/NormalActivity.java](NormalAcvitiy)

**Comment by Dhy521** [comment]
就是点击按钮 就相当于左滑和右滑事件   你这个demo怎么使用阿  装数据是否方便阿？能否用这个适配器BaseRecyclerViewApadterHelper?

**Comment by Dhy521** [comment]
我引入的话 布局是否支持自定义阿?

**Comment by JerryChan123** [comment]
具体的操作步骤告诉我，也可以加我qq：363040336

**Comment by Dhy521** [comment]
请问一下  怎么做数据加载呢  就是我刷到最后一个 哪个方法是继续添加数据呢

**Comment by JerryChan123** [comment]
跟常规RecyclerView添加数据一样的
